### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by senzacionale** [coinigy/PureWebSockets#12]
I am getting after while error message from web socket provider "The remote party closed the WebSocket connection without completing the close handshake."

Is it possible somehow to catch this exception and handle it and properly close it?

Unfortunately this exception is not cached with " _webSocket.OnError += _webSocket_OnError;"

**Comment by ByronAP** [comment]
What version and are you using an auto-reconnect strategy?

**Comment by senzacionale** [comment]
I am not using auto-reconnect strategy because I want to manually handle it.

I am using last version 2.3.0

**Comment by ByronAP** [comment]
Ok this may be a side effect of the recent change to suppress disconnects when using auto reconnect. Will investigate further and get back to you.

**Comment by senzacionale** [comment]
Great, thank you.

**Comment by ByronAP** [comment]
Can you tell me what happens when this does occur? do you just see it in debug log or do you get some other event?

**Comment by senzacionale** [comment]
I just see it in debug log yes. No other events.
