### ISSUE TITLE
Reliability issues ?

### ISSUE THREAD

**Issue by eltomjan** [coinigy/PureWebSockets#14]
Hello,

I had strange problems using the lib - when server is stopped or down, it ends with and exception and no way to cleanup properly (another during dispose - closing in connecting state?), even during reconnect with "random" server restarting it sometimes end in a strange state, then found there are at least 2 places (line 322, 326) where monitor silently exits, so it is a bit stucked then.
I end up almost rewriting it, now my monitor has a "never-ending" loop and it works quite fine - can start reconnect attempts even without running server and nicely restarts when server stops and starts again... Thought I will try it in original version first, but it was very hard for me to find and test all problematic scenarios/behavior in existing logic. Btw not sure where you made it, but on windows it just duplicate some features - there is a connect timeout already, etc. And also it looks better in logs if communication ends with something like CloseAsync/CloseWithHandshake on client/server side to prevent error messages like missing handshake, socket error, etc.

**Comment by ByronAP** [comment]
feel free to make a PR, the disconnect issue is a known bug  #12
