### ISSUE TITLE
Non-copyleft license?

### ISSUE THREAD

**Issue by VictorBlomberg** [coinigy/PureWebSockets#7]
Hi,

I saw this library, which seems very interesting. Unfortunately the GPL license doesn’t fit the intended usage for me. I suppose it's out of the question to consider a non-copyleft license?

Thank you regardless for making this FLOSS contribution,
and have a nice day!

**Comment by ByronAP** [comment]
Why? If you are looking to copy and sell that is out of the question. If you would like a custom copyrighted library you would have to hire me to make one.

**Comment by VictorBlomberg** [comment]
Thank you for your quick reply!

The intended use would be to use this library as a (smaller) part of a large proprietary software. The GPL license would require the complete software using this library to also be licensed under a GPL compatible license. [1] [2]
That is not possible in my case, and a permissive (non-copyleft) license would not make that requirement, hence my question. I do of course fully respect if you are unwilling to do so.

(With that said, even the GPL license currently used allows me to sell your software, although only using the same license (GPL).)

[1] https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29
[2] https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem

**Comment by VictorBlomberg** [comment]
Hi, sorry to disturb you again. I suppose I could see this as a 'no' to change license?

Thank you for your time in any case,
